version: "3.7"
services:
    mosquitto:
      image: eclipse-mosquitto:2.0.18
      ports:
        - 1883:1883
      volumes:
        - ./mosqquito/conf:/mosquitto/config
        - ./mosqquito/data:/mosquitto/data
        - ./mosqquito/log:/mosquitto/log
    influxdb:
        image: influxdb:2.0.7
        ports:
          - 8086:8086
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: iot
            DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET} 
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}