version: "3.7"
services:
    influxdb:
        image: influxdb:2.0.7
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: iot
            DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        ports:
            - "8086:8086"
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.3G'

    app:
        image: lakky1/iot_server_url_manage:latest
        ports:
            - "8080:8080"
        environment:
            DB_URL: http://influxdb:8086
            INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
            INFLUXDB_ORG: iot  
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        depends_on:
            - influxdb
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.3G'

    grafana:
        image: grafana/grafana-oss:main
        ports:
            - 3000:3000
        depends_on:
            - influxdb
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.3G'

    slack-bot:
        image: lakky1/iot_server_url_manage:latest
        environment:
            IS_COMPOSE: true
            SLACK_BOT_OAUTH: ${SLACK_BOT_OAUTH}
        depends_on:
            - ngrok_app
            - ngrok_monitor
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.3G'
